=== Tmattsson0/thesis_task_set_generation/schema_task_generation.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "environment": {
      "type": "object",
      "properties": {
        "number_of_hosts": {
          "type": "integer"
        },
        "schedule_type": {
          "type": "string"
        },
        "preemptible": {
          "type": "boolean"
        },
        "num_of_cores": {
          "type": "integer"
        },
        "microtick_values": {
          "type": "integer"
        }
      },
      "required": [
        "number_of_hosts",
        "schedule_type",
        "preemptible",
        "num_of_cores",
        "microtick_values"
      ]
    },
    "system": {
      "type": "object",
      "properties": {
        "tt_utilization": {
          "type": "number"
        },
        "et_utilization": {
          "type": "number"
        },
        "num_of_tt_tasks": {
          "type": "integer"
        },
        "num_of_et_tasks": {
          "type": "integer"
        },
        "periods": {
          "type": "array",
          "items": [
            {
              "type": "array",
              "items": [
                {
                  "type": "integer"
                },
                {
                  "type": "number"
                }
              ]
            },
            {
              "type": "array",
              "items": [
                {
                  "type": "integer"
                },
                {
                  "type": "number"
                }
              ]
            }
          ]
        }
      },
      "required": [
        "tt_utilization",
        "et_utilization",
        "num_of_tt_tasks",
        "num_of_et_tasks",
        "periods"
      ]
    },
    "task": {
      "type": "object",
      "properties": {
        "allowed_jitter": {
          "type": "number"
        },
        "release_time": {
          "type": "number"
        },
        "deadline_type": {
          "type": "string"
        }
      },
      "required": [
        "allowed_jitter",
        "release_time",
        "deadline_type"
      ]
    },
    "chain": {
      "type": "object",
      "properties": {
        "num_of_chains": {
          "type": "integer"
        },
        "num_of_tasks_in_chain": {
          "type": "integer"
        },
        "num_of_low": {
          "type": "integer"
        },
        "num_of_high": {
          "type": "integer"
        },
        "num_of_host_transitions": {
          "type": "integer"
        },
        "latency": {
          "type": "number"
        }
      },
      "required": [
        "num_of_chains",
        "num_of_tasks_in_chain",
        "num_of_low",
        "num_of_high",
        "num_of_host_transitions",
        "latency"
      ]
    }
  },
  "required": [
    "environment",
    "system",
    "task",
    "chain"
  ]
}

=== Tmattsson0/thesis_task_set_generation/config/parameters.json
{
  "environment": {
    "number_of_hosts": 1,
    "schedule_type": "",
    "preemptible": true,
    "num_of_cores": 1,
    "microtick_values": 1
  },
  "system": {
    "tt_utilization": 2.2,
    "et_utilization": 2.2,
    "num_of_tt_tasks": 1,
    "num_of_et_tasks": 1,
    "periods":
            [[100, 2.0],
            [100, 3.0]]
  },
  "task": {
    "allowed_jitter": 2.2,
    "release_time": 2.2,
    "deadline_type": ""
  },
  "chain": {
    "num_of_chains": 1,
    "num_of_tasks_in_chain": 1,
    "num_of_low": 1,
    "num_of_high": 1,
    "num_of_host_transitions": 1,
    "latency": 2.2
  }
}
